# Production image: frontend static export served by FastAPI, one deployable
# process (frontend/next.config.ts, plan.md Structure Decision).
#
# docker build -t clinical-decision-support .
# docker run -p 8000:8000 --env-file .env -v $(pwd)/data:/app/data clinical-decision-support

# --- Stage 1: build the Next.js static export ---
FROM node:20-slim AS frontend-build
WORKDIR /app/frontend
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend .
RUN NODE_ENV=production npm run build

# --- Stage 2: backend + static frontend ---
FROM python:3.13-slim AS runtime
WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY backend ./backend
COPY data/sources.yaml ./data/sources.yaml
COPY data/corpus ./data/corpus
COPY --from=frontend-build /app/frontend/out ./frontend/out

# The entrypoint builds the index on first boot if the volume is empty.
# sed strips CRLF so the script still runs when the build context came from
# a Windows checkout (otherwise Linux reports a bogus "no such file" error).
COPY docker-entrypoint.sh /app/docker-entrypoint.sh
RUN sed -i 's/\r$//' /app/docker-entrypoint.sh && chmod +x /app/docker-entrypoint.sh

# .env supplied at runtime; data/index is a volume, generated by `ingest`.
EXPOSE 8000

# start-period covers first-boot ingest, which takes ~35s for NG243.
HEALTHCHECK --interval=30s --timeout=5s --start-period=120s --retries=3 \
    CMD curl -f http://localhost:8000/api/health || exit 1

ENTRYPOINT ["/app/docker-entrypoint.sh"]
